import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/styles.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: {
    default: "BNN Kuningan",
    template: "%s | BNN Kuningan",
  },
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/images/bnn-logo.svg", sizes: "32x32", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster
            position={"top-right"}
            reverseOrder={false}
            toastOptions={{
              success: {
                style: {
                  background: "oklch(96.2% 0.044 156.743)",
                },
              },
              error: {
                style: {
                  background: "oklch(93.6% 0.032 17.717)",
                },
              },
            }}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
